name: Actions WorkFlow

on:
  push:

jobs:
  DISPLAY_ACTIONS:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
      - name: CheckOut Repository
        uses: actions/checkout@v1

      - name: List Files After Checkout
        run: |
          pwd
          ls -a
